name: KingOfTheHill
author: piyushbest
description: Simple King Of The Hill PMMP Plugin
version: 1.0.0
main: koth\KothMain
api: 3.0.0
commands:
  koth:
    usage: "/koth help"
    description: "Koth Commands For King Of The Hill"
    permission: koth.*
