name: KingOfTheHill
author: QuiltedTuba2978
description: Simple King Of The Hill PMMP Plugin
version: 1.0.0
main: koth\KothMain
api:
- 3.0.0-ALPHA10
- 3.0.0-ALPHA11
- 3.0.0-ALPHA12
commands:
  koth:
    usage: "/koth help"
    description: "Koth Commands For King Of The Hill"
    permission: koth.*
